name: XHS Watcher

on:
  schedule:
    - cron: "0 * * * *"   # 每小时，按需改
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Playwright browsers and required system deps (Python version)
      - name: Install Playwright browsers and deps
        run: |
          python -m playwright install --with-deps chromium

      # （可选）恢复上次运行的去重文件
      - name: Restore last seen file (artifact)
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: xhs.yml
          workflow_conclusion: success
          name: xhs-seen
          path: .
        continue-on-error: true

      - name: Ensure seen file exists
        run: |
          test -f xhs_seen.json || echo "[]" > xhs_seen.json

      - name: List workspace for debugging
        run: |
          pwd
          ls -la

      - name: Run watcher (single pass)
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID:   ${{ secrets.TG_CHAT_ID }}
          KEYWORDS:     ${{ secrets.KEYWORDS }}
          XHS_COOKIE:   ${{ secrets.XHS_COOKIE }}
          HEADLESS:     "1"
        run: |
          set -e
          python xhs_watch.py || echo "Script failed but proceeding to upload artifact"

      - name: Upload seen file for next runs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xhs-seen
          path: ./xhs_seen.json
          if-no-files-found: warn
          retention-days: 90


